name: SItemDB
author: solo
version: 1.0.0
api: [3.0.0, 3.1.0, 4.0.0]
main: solo\sitemdb\SItemDB
permissions:
  sitemdb:
    default: op
    children:
      sitemdb.command:
        default: op
        children:
          sitemdb.command.itemcopy:
            default: op
          sitemdb.command.itemgive:
            default: op
          sitemdb.command.itemlore:
            default: op
          sitemdb.command.itemname:
            default: op
          sitemdb.command.itemregister:
            default: op
          sitemdb.command.itemsearch:
            default: op
          sitemdb.command.itemunregister:
            default: op
          sitemdb.command.itemview:
            default: op
